sudo: required

language: php

services:
  - docker

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  - AMP_DEBUG=true

before_install:
  - docker pull php:7.1
  - docker pull crossbario/autobahn-testsuite

install:
  - composer update -n --prefer-dist

  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.2/coveralls.phar
  - chmod +x coveralls.phar

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix
  - docker run -d --rm -v ${PWD}:/app --net="host" --name aerys php:7.1 php /app/bin/aerys -c /app/test-autobahn/server.php
  - docker run -ti --rm -v ${PWD}/test-autobahn/config:/config -v ${PWD}/test-autobahn/reports:/reports --net="host" --name fuzzingclient crossbario/autobahn-testsuite wstest -m fuzzingclient

after_script:
  - ./coveralls.phar -v

cache:
  directories:
    - $HOME/.composer/cache
